apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: camel-solace-pubsub-test
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/bszeti/camel-solace-pubsub-test.git'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'registry.redhat.io/fuse7/fuse-java-openshift-rhel8:1.11'
      env: []
  triggers:
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: camel-solace-pubsub-test:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: camel-solace-pubsub-test
spec:
  # Makes it possible to use image: "camel-solace-pubsub-test:latest" in Pod spec within the build namespace
  lookupPolicy:
    local: true


